from app.schemas.agent import AgentExecutionRequest, AgentExecutionResult
from app.services.agents.base import AgentProvider


class MockAgentProvider(AgentProvider):
    name = "mock"

    def execute(self, request: AgentExecutionRequest) -> AgentExecutionResult:
        priority = "high" if request.input_payload.get("amount", 0) and request.input_payload.get("amount", 0) > 5000 else "normal"

        recommendation = {
            "summary": "Automation proposal generated by mock provider",
            "priority": priority,
            "suggested_actions": [
                "validate_context",
                "prepare_handoff_payload",
                "trigger_operational_workflow",
            ],
            "input_echo": request.input_payload,
        }

        tool_calls: list[dict] = []
        if request.tools:
            first_tool = request.tools[0]
            tool_calls.append(
                {
                    "tool_name": first_tool.name,
                    "arguments": {
                        parameter.name: request.input_payload.get(parameter.name)
                        for parameter in first_tool.parameters
                    },
                }
            )

        return AgentExecutionResult(
            provider=self.name,
            model=request.model or "mock-agent-v1",
            output=recommendation,
            tool_calls=tool_calls,
            input_tokens=120,
            output_tokens=80,
            cost_usd=0.0,
        )
